### ISSUE TITLE
Display confirmations progress to user on Bridge Deposit

### ISSUE THREAD

**Issue by aidan-starke** [cennznet/app-hub#127]

**Comment by ken-centrality** [comment]
Need to understand a bit more about the confirmations progress and how's that important for users to know.

**Comment by aidan-starke** [comment]
on testnets deposit claim needs to be confirmed by 3 validators, 10 on Azalea,
it was a feature request from Jordy - I think because getting 10 confirmations can take a while its a nice-to-have so the user doesn't think the transaction is just hanging

**Comment by ken-centrality** [comment]
updated milestones to `1.0.x`, we are gonna revamp this a bit on the next iteration
