### ISSUE TITLE
Adding max liquidity fails

### ISSUE THREAD

**Issue by aidan-starke** [cennznet/app-hub#15]
Add Liquidity transaction fails when using MAX button - I think slippage is causing the transaction to fall outside of available balance

**Comment by ken-centrality** [comment]
@eupston to confirm if this is a `bug` or a `feature`

**Comment by eupston** [comment]
Yeah have confirmed this is a feature. The warning we present under the settings is meant to warn the user if the transaction may fails. 

<img width="613" alt="Screen Shot 2022-02-20 at 5 56 39 PM" src="https://user-images.githubusercontent.com/35315320/154872877-5fc4ba26-114f-48ab-b33c-3e3a9d6fc882.png">

**Comment by ken-centrality** [comment]
okay, so does that mean we have to adjust the value of "Max" when people want to put everything in?

**Comment by eupston** [comment]
yeah that was what I originally suggested but after chatting with Jordy and Karshima, we decided to display the above warning box with potential about transaction failing for time being.

**Comment by ken-centrality** [comment]
sweet, closing it
