### ISSUE TITLE
Styling issues in Bridge section

### ISSUE THREAD

**Issue by ken-centrality** [cennznet/app-hub#21]
- [ ] (1) Remove "Enter Amount" label, don't think we need it
- [ ] (2) Have the "Destination" label on the top like others, and remove the placeholder one
- [ ] (3) Missing the option to enter different address
- [ ] (4) Metamask icon looks a bit blurry, can we use SVG version if there is one?
- [ ] (5) I should have picked this up in the design, but should this FROM -> TO, rather TO -> FROM?

![Screen Shot 2022-02-15 at 08 17 08](https://user-images.githubusercontent.com/97480229/153938508-d9080b8a-99a5-44e4-a31f-ade9dc6b42c6.png)

**Comment by eupston** [comment]
yup sounds good, totally agree about the TO and FROM was thinking exact same thing.
These should all be resolved in the next PR
