### ISSUE TITLE
Refresh the app  on Vercel cause the wallet show empty state with error

### ISSUE THREAD

**Issue by ken-centrality** [cennznet/app-hub#32]
![Screen Shot 2022-02-16 at 09 13 25](https://user-images.githubusercontent.com/97480229/154144979-83d18009-f8c7-47e2-8d4e-ca99c643cac4.png)

**Comment by aidan-starke** [comment]
Can't reproduce this error

**Comment by ken-centrality** [comment]
seems to resolved since #80
