### ISSUE TITLE
In Pool section, add more copy in the Status box

### ISSUE THREAD

**Issue by ken-centrality** [cennznet/app-hub#77]
```
You will earn x% of all trades on this pair proportional to your share of the pool
```

Similar to what PancakeSwap does
<img width="418" alt="Screen Shot 2022-02-24 at 10 51 27" src="https://user-images.githubusercontent.com/97480229/155414752-08c0b165-4fb6-4ae2-b1be-e8e849d912b0.png">

**Comment by aidan-starke** [comment]
<img width="724" alt="Screen Shot 2022-03-01 at 7 10 22 AM" src="https://user-images.githubusercontent.com/52016903/156035517-4a654772-4ac0-46b4-8881-407a937ea4ba.png">

If I'm understanding this correctly, we can say 

> You will earn 0.3% of all trades on this pair proportional to your share of the pool
