### ISSUE TITLE
Update contracts from peg-fix

### ISSUE THREAD

**Issue by aidan-starke** [cennznet/app-hub#89]
Need to update:
 - Bridge & Peg contract addresses
 - Peg ABI
 - Add validators to withdraw proof

**Comment by holygits** [comment]
need to add a check when converting validator addresses that the pubkey is not 0s as this will cause `computeAddress` to throw:
https://github.com/cennznet/bridge-ui/commit/e9f9cbf2e943e9eb45fc6e3f4f19756f1ad001e2
